version: '3.8'
services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS financas
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: sa
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
      JWT_EXPIRACAO: 30
      JWT_CHAVE_ASSINATURA: YSBsZWJyZSDDqSBicmFuY2E=